# Generated by Django 5.0.2 on 2024-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1),
        ),
    ]
