# Generated by Django 5.0.2 on 2024-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Software Developer', 'Software Developer'), ('Project Leader', 'Project Leader')], max_length=50),
        ),
    ]
