# Generated by Django 5.0.2 on 2024-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_companies_type_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='type',
            field=models.CharField(choices=[('Non IT', 'Non IT'), ('IT', 'IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
