# Generated by Django 5.0.2 on 2024-02-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_companies_name_alter_companies_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='account.companies'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Project Leader', 'Project Leader'), ('Manager', 'Manager'), ('Software Developer', 'Software Developer')], max_length=50),
        ),
    ]
