# Generated by Django 5.0.2 on 2024-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_employees_company_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Manager', 'Manager'), ('Project Leader', 'Project Leader')], max_length=50),
        ),
    ]
