# Generated by Django 5.0.2 on 2024-02-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Project Leader', 'Project Leader'), ('Software Developer', 'Software Developer'), ('Manager', 'Manager')], max_length=50),
        ),
    ]
