# Generated by Django 5.0.2 on 2024-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_companies_type_alter_employees_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='added_date',
        ),
        migrations.AlterField(
            model_name='companies',
            name='type',
            field=models.CharField(choices=[('Non IT', 'Non IT'), ('IT', 'IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Manager', 'Manager'), ('Project Leader', 'Project Leader')], max_length=50),
        ),
    ]
